language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt
# command to run tests
script:
  - cd tests
  - python run.py
